# .air.local.toml for local Go hot reload
root = "."

[build]
  cmd = "go build -o tmp/main ./cmd/main.go"
  bin = "tmp/main"
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["vendor", "pgdata"]
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[run]
  cmd = "tmp/main"
  stop_on_error = true
